"""Python client for Korea Environment Corporation AirKorea APIs."""

from pyairkorea.client import SUPPORTED_ENDPOINTS, AirKoreaClient
from pyairkorea.codes import (
    AirQualityGrade,
    DataTerm,
    InformCode,
    Pollutant,
    SidoName,
    StatsDataGubun,
    StatsSearchCondition,
)
from pyairkorea.coords import (
    LatLon,
    LatLonLike,
    TmPoint,
    TmPointLike,
    coerce_latlon,
    coerce_tm_point,
    resolve_airkorea_tm,
    tm_to_wgs84,
    wgs84_to_tm,
)
from pyairkorea.exceptions import (
    AirKoreaAuthError,
    AirKoreaError,
    AirKoreaNetworkError,
    AirKoreaNoDataError,
    AirKoreaParseError,
    AirKoreaRateLimitError,
    AirKoreaRequestError,
    AirKoreaServerError,
)
from pyairkorea.metadata import (
    is_credential_param,
    make_cache_key,
    make_call_context,
    sanitize_request_params,
)
from pyairkorea.models import (
    AdvisoryOccurrence,
    AirKoreaCallContext,
    AirKoreaModel,
    AirKoreaPage,
    AirQualityMeasurement,
    AirQualityStat,
    BackgroundConcentration,
    CaiMeasurement,
    DustAlarm,
    EnglishAirQualityMeasurement,
    EnglishStation,
    ForecastNotice,
    HighPm25Forecast,
    NearbyStation,
    RawRecord,
    Station,
    TmCoordinate,
    TrafficStat,
    WeeklyForecastNotice,
)
from pyairkorea.pagination import has_next_page, iter_paginated_pages, next_page_no

__version__ = "0.4.0"

__all__ = [
    "AirKoreaAuthError",
    "AirKoreaCallContext",
    "AirKoreaClient",
    "AirKoreaError",
    "AirKoreaNetworkError",
    "AirKoreaNoDataError",
    "AirKoreaParseError",
    "AirKoreaPage",
    "AirKoreaRateLimitError",
    "AirKoreaRequestError",
    "AirKoreaServerError",
    "AirKoreaModel",
    "AirQualityGrade",
    "AirQualityMeasurement",
    "AirQualityStat",
    "AdvisoryOccurrence",
    "BackgroundConcentration",
    "CaiMeasurement",
    "DataTerm",
    "DustAlarm",
    "EnglishAirQualityMeasurement",
    "EnglishStation",
    "ForecastNotice",
    "HighPm25Forecast",
    "InformCode",
    "LatLon",
    "LatLonLike",
    "NearbyStation",
    "Pollutant",
    "RawRecord",
    "SidoName",
    "Station",
    "StatsDataGubun",
    "StatsSearchCondition",
    "SUPPORTED_ENDPOINTS",
    "TmCoordinate",
    "TmPoint",
    "TmPointLike",
    "TrafficStat",
    "WeeklyForecastNotice",
    "__version__",
    "coerce_latlon",
    "coerce_tm_point",
    "has_next_page",
    "is_credential_param",
    "iter_paginated_pages",
    "make_cache_key",
    "make_call_context",
    "next_page_no",
    "resolve_airkorea_tm",
    "sanitize_request_params",
    "tm_to_wgs84",
    "wgs84_to_tm",
]
